source ~/.vim/configs/basics.vim
source ~/.vim/configs/plugins.vim

"Anything that are used privately goes to this file
if !empty(glob("~/.vim/configs/extended.vim"))
  source ~/.vim/configs/extended.vim
endif

nnoremap <leader>ev :split $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

"Auto load after save
autocmd! bufwritepost .vimrc source %
