# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
eval "$(oh-my-posh --init --shell zsh --config  ${HOME}/.omp-theme/nahnuj.omp.json)"

ZSH_DISABLE_COMPFIX=True
export ZSH="$HOME/.oh-my-zsh"
# ZSH_THEME="nahnuj"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR=vim
export VISUAL=vim

# used for .vimrc
HOSTNAME=$(hostname)

# Keybindings
bindkey -v
export KEYTIMEOUT=1

bindkey '^w' backward-kill-word
bindkey '^d' delete-char
bindkey '^k' kill-line
bindkey '^h' backward-delete-char

bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward
bindkey '^p' up-history
bindkey '^n' down-history

bindkey '^f' forward-char
bindkey '^b' backward-char
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# readline for compilers, maybe used when run Ruby bundle
export LDFLAGS="-L/opt/homebrew/opt/readline/lib"
export CPPFLAGS="-I/opt/homebrew/opt/readline/include"


# ENV extensions
# Python: virtualenv
export WORKON_HOME='~/.virtualenvs'
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# Ruby: rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Javascript: nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Rosetta2
# Brew python path
alias ibrew="arch -x86_64 /usr/local/bin/brew" # Homebrew on Rosetta2
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
# Homebrew on the M1, where things install to /opt/homebrew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/local/opt/rabbitmq/sbin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

# zsh 
alias zsh64="arch -x86_64 zsh"

# flutter
export PATH="$HOME/Documents/flutter/bin:$PATH"

# tmux
alias tmux="tmux -u" # use UTF-8 in tmux to support powerline

