export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR=vim
export VISUAL=vim

# Vim mode
export KEYTIMEOUT=1
bindkey -v

bindkey '^w' backward-kill-word
bindkey '^d' delete-char
bindkey '^k' kill-line
bindkey '^h' backward-delete-char

bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward
bindkey '^p' up-history
bindkey '^n' down-history

bindkey '^f' forward-char
bindkey '^b' backward-char
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# fnm enables node and npm (newer than nvm)
eval "$(fnm env)"

PATH=~/.console-ninja/.bin:$PATH

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# tmux
alias tmux="tmux -u" # use UTF-8 in tmux to support powerline

# Git
alias gll="git log --oneline --decorate --graph -5"

# functions
function update_git_config {
  local name="Junhan"
  local email="z@junhan.xyz"
  git config user.name "${name}"
  git config user.email "${email}"
  echo "Updated:\nname: ${name}\nemail: ${email}"
}
